### ISSUE TITLE
Deploy xbim on linux

### ISSUE THREAD

**Issue by fangfj2002** [xBimTeam/XbimExchange#28]
I want to use xbim.exchange to convert ifc files to wexbim and json files on linux. 
Can somebody tell me how to do that.

**Comment by LloydPickering** [comment]
It is not currently possible to run Xbim itself on Linux. You could use Xbim on Windows to generate artifacts such as Wexbim and/or Json and then consume that on Linux. There are existing examples on how to generate Wexbim files. It would then be up to you to figure out how you wanted to consume them on Linux

**Comment by andyward** [comment]
Take a look at the https://github.com/xBimTeam/XbimCobieExpress sister project which runs under .NET Core on Linux.

**Comment by simiii** [comment]
@fangfj2002 have you ever found a solution to this problem?

**Comment by cartantino** [comment]
Hello everyone, 
are there any news on this topic?

**Comment by andyward** [comment]
As mentioned above, if you want to work with COBie under Linux, take a look at https://github.com/xBimTeam/XbimCobieExpress

If you want to generate wexbim etc under Linux that's a different challenge. There's no easy solution since even the latest xbimGeometry net6/8 is still Windows only due to the reliance on C++/CLI for the OpenCascade interop.
