### ISSUE TITLE
STEP to IFC

### ISSUE THREAD

**Issue by Ludivan** [xBimTeam/XbimExchange#41]
Hello,

I have an application (Inventor) that exports properly to STEP but not really to IFC.

Would it be possible to use XBIM to import a STEP file and build a IFC file in which we would add / reorganize the metadata ?

Thanks
Best regards
Luc

**Comment by andyward** [comment]
Even though IFC is based on STEP it'd be a big job to create a translator as we'd have to map between the different STEP data types from the 'product' world and the nearest buildingSmart IFC equivalents

According to Autodesk, Inventor has been able to export to IFC2x3 since version 2016. Are you sure you're not able to do the conversion in Inventor (or is it the case that it makes a poor job of it because it)?

**Comment by Ludivan** [comment]
You are right, Inventor can export to IFC, but the export is more than basic and results into a single object (assembly hierarchy and relative parts attributes not translated).

Anyway thank you very much taking the time to answer me and thinking about my problem, its really appreciated.
Best regards
Luc

**Comment by Ludivan** [comment]
I agree, this is why I think during the exportation I would let the user choose which category to give to each component.
Without this mapping work, would XBIM be able to create a "blank" IFC (just geometry data) ?
